[features]
seeds = false
skip-lint = false
[programs.devnet]
ticket_system = "3ShEbfCKTDmdX8NSX5kmG9H5Cms4G4HYT8ZbYKhPYdxW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
system = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/System/SystemAccount.ts"
event = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/CreateEvents.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/CheckEvent.ts"
ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/BuyATicket.ts"
checks = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/System/CheckSystem.ts"