[features]
seeds = false
skip-lint = false
[programs.devnet]
ticket_system = "DvrXsDmz9cBLbLsCun9a37ojkCaxG1hxSAJsg36yttu7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
system = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/System/SystemAccount.ts"
event = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/CreateEvents.ts"
